name: urban_sound_art_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  data_table_2: ^2.3.10
  flutter_custom_dialog: ^1.3.0
  date_time_picker: ^2.1.0
  firebase_storage: ^11.0.10
  firebase_storage_web: ^3.3.19
  image_picker: ^0.8.6+1
  flutter_sound: ^9.2.13
  easy_audio_player: ^0.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

